# ============================================================
# GRUVBOX MATERIAL — SOFT LIGHT
# ============================================================

background #f2e5bc
foreground #3c3836

selection_background #d5c4a1
selection_foreground #3c3836

cursor #9d6500
cursor_text_color #f2e5bc

url_color #076678

active_border_color #b57614
inactive_border_color #d5c4a1


# ============================================================
# ANSI
# ============================================================

color0  #f2e5bc
color1  #9d0006
color2  #79740e
color3  #b57614
color4  #076678
color5  #8f3f71
color6  #427b58
color7  #504945

color8  #928374
color9  #9d0006
color10 #79740e
color11 #b57614
color12 #076678
color13 #8f3f71
color14 #427b58
color15 #3c3836


# ============================================================
# TABS
# ============================================================

active_tab_foreground #f2e5bc
active_tab_background #b57614

inactive_tab_foreground #504945
inactive_tab_background #d5c4a1
