cursor #654735
cursor_text_color #4f3829

foreground            #654735
background            #f2e5bc
selection_foreground  #ebdbb2
selection_background  #c35e0a
url_color             #6c782e

color0   #ebdbb2
color1   #792b1f
color2   #065304
color3   #534500
color4   #3c4c00
color5   #6f8352
color6   #6c782e
color7   #222321
color8   #9fa09c
color9   #99473a
color10  #1a7616
color11  #756500
color12  #5c6d0a
color13  #606b2a
color14  #949c6b
color15  #bdbfba
