cursor #d8c7a5
cursor_text_color #cbb995

foreground            #d8c7a5
background            #302e2b
selection_foreground  #252321
selection_background  #d7834f
url_color             #9eac62

color0   #252321
color1   #a34f41
color2   #35812d
color3   #ceb733
color4   #a5b463
color5   #f8ffdb
color6   #9eac62
color7   #2f302e
color8   #91928e
color9   #ce7567
color10  #5fbd55
color11  #dfc843
color12  #b4c568
color13  #f8ffdb
color14  #d6dfaf
color15  #fefff9
