-- DMS user keybind overrides (edit via Control Center or dms; do not remove this header)

hl.unbind("SUPER + C")
hl.bind("SUPER + C", hl.dsp.exec_cmd("exec dms ipc call dash toggle \"\""))
hl.unbind("SUPER + CTRL + N")
hl.bind("SUPER + CTRL + N", hl.dsp.exec_cmd("dms ipc call notifications toggle"), { description = "dms ipc call notifications toggle" })
hl.unbind("SUPER + Ccedilla")
hl.bind("SUPER + Ccedilla", hl.dsp.exec_cmd("dms ipc call settings focusOrToggle"), { description = "dms ipc call settings focusOrToggle" })
hl.unbind("SUPER + D")
hl.bind("SUPER + D", hl.dsp.exec_cmd("dms ipc call control-center toggle"), { description = "Control Center: Toggle" })
hl.unbind("SUPER + SHIFT + S")
hl.bind("SUPER + SHIFT + S", hl.dsp.exec_cmd("dms screenshot"), { description = "dms screenshot" })
hl.unbind("SUPER + W")
hl.bind("SUPER + W", hl.dsp.exec_cmd("dms ipc call dash toggle wallpaper"), { description = "dms ipc call dash toggle wallpaper" })
hl.unbind("SUPER + 0")
hl.bind("SUPER + 0", hl.dsp.focus({ workspace = "10" }), { description = "Focus Workspace" })
hl.unbind("SUPER + CTRL + 0")
hl.bind("SUPER + CTRL + 0", hl.dsp.window.move({ workspace = "10", follow = false }), { description = "Move to Workspace (silent)" })
hl.unbind("SUPER + CTRL + 1")
hl.bind("SUPER + CTRL + 1", hl.dsp.window.move({ workspace = "1", follow = false }), { description = "Move to Workspace (silent)" })
hl.unbind("SUPER + CTRL + 2")
hl.bind("SUPER + CTRL + 2", hl.dsp.window.move({ workspace = "2", follow = false }), { description = "move to workspace 1" })
hl.unbind("SUPER + CTRL + 3")
hl.bind("SUPER + CTRL + 3", hl.dsp.window.move({ workspace = "3", follow = false }), { description = "Move to Workspace (silent)" })
hl.unbind("SUPER + CTRL + 4")
hl.bind("SUPER + CTRL + 4", hl.dsp.window.move({ workspace = "4", follow = false }), { description = "Move to Workspace (silent)" })
hl.unbind("SUPER + CTRL + 5")
hl.bind("SUPER + CTRL + 5", hl.dsp.window.move({ workspace = "5", follow = false }), { description = "Move to Workspace (silent)" })
hl.unbind("SUPER + CTRL + 9")
hl.bind("SUPER + CTRL + 9", hl.dsp.window.move({ workspace = "9", follow = false }), { description = "Move to Workspace (silent)" })
hl.unbind("SUPER + SHIFT + 0")
hl.bind("SUPER + SHIFT + 0", hl.dsp.window.move({ workspace = "10" }), { description = "Move to Workspace 0" })
hl.unbind("SUPER + ALT + H")
hl.bind("SUPER + ALT + H", hl.dsp.window.resize({ x = -100, y = 0, relative = true }), { repeating = true, description = "Resize window by -100 0" })
hl.unbind("SUPER + ALT + J")
hl.bind("SUPER + ALT + J", hl.dsp.window.resize({ x = 0, y = 100, relative = true }), { repeating = true, description = "Resize Active Window" })
hl.unbind("SUPER + ALT + K")
hl.bind("SUPER + ALT + K", hl.dsp.window.resize({ x = 0, y = -100, relative = true }), { repeating = true, description = "Resize window by 0 -100" })
hl.unbind("SUPER + ALT + L")
hl.bind("SUPER + ALT + L", hl.dsp.window.resize({ x = 100, y = 0, relative = true }), { repeating = true, description = "Resize window by 100 0" })
hl.unbind("SUPER + CTRL + H")
hl.bind("SUPER + CTRL + H", hl.dsp.window.move({ direction = "l" }), { description = "move in left direction" })
hl.unbind("SUPER + CTRL + J")
hl.bind("SUPER + CTRL + J", hl.dsp.window.move({ direction = "d" }), { description = "move in down direction" })
hl.unbind("SUPER + CTRL + K")
hl.bind("SUPER + CTRL + K", hl.dsp.window.move({ direction = "u" }), { description = "move in up direction" })
hl.unbind("SUPER + CTRL + L")
hl.bind("SUPER + CTRL + L", hl.dsp.window.move({ direction = "r" }), { description = "move in right direction" })
hl.unbind("SUPER + A")
hl.bind("SUPER + A", hl.dsp.exec_cmd("exec flatpak run net.ankiweb.Anki"), { description = "anki" })
hl.unbind("SUPER + B")
hl.bind("SUPER + B", hl.dsp.exec_cmd("firefox"), { description = "browser" })
hl.unbind("SUPER + CTRL + M")
hl.bind("SUPER + CTRL + M", hl.dsp.exec_cmd("kitty -e waxon"))
hl.unbind("SUPER + E")
hl.bind("SUPER + E", hl.dsp.exec_cmd("exec dcal"), { description = "calendar" })
hl.unbind("SUPER + M")
hl.bind("SUPER + M", hl.dsp.exec_cmd("kitty -e cliamp"), { description = "ncspot" })
hl.unbind("SUPER + N")
hl.bind("SUPER + N", hl.dsp.exec_cmd("kitty -e nvim"))
hl.unbind("SUPER + O")
hl.bind("SUPER + O", hl.dsp.exec_cmd("exec flatpak run md.obsidian.Obsidian"), { description = "obsidian" })
hl.unbind("SUPER + Return")
hl.bind("SUPER + Return", hl.dsp.exec_cmd("kitty"), { description = "Terminal" })
hl.unbind("SUPER + S")
hl.bind("SUPER + S", hl.dsp.exec_cmd("exec flatpak run com.github.ahrm.sioyek"), { description = "sioyek" })
hl.unbind("SUPER + SHIFT + A")
hl.bind("SUPER + SHIFT + A", hl.dsp.exec_cmd("firefox --new-tab https://aprovadoapp.com/"), { description = "aprovado" })
hl.unbind("SUPER + SHIFT + B")
hl.bind("SUPER + SHIFT + B", hl.dsp.exec_cmd("helium"))
hl.unbind("SUPER + SHIFT + C")
hl.bind("SUPER + SHIFT + C", hl.dsp.exec_cmd("helium https://chatgpt.com/"), { description = "chat" })
hl.unbind("SUPER + SHIFT + D")
hl.bind("SUPER + SHIFT + D", hl.dsp.exec_cmd("helium https://drive.google.com/drive/u/0/my-drive"), { description = "drive" })
hl.unbind("SUPER + SHIFT + E")
hl.bind("SUPER + SHIFT + E", hl.dsp.exec_cmd("firefox https://www.estrategiaconcursos.com.br/app/dashboard/cursos"), { description = "estratégia" })
hl.unbind("SUPER + SHIFT + G")
hl.bind("SUPER + SHIFT + G", hl.dsp.exec_cmd("exec firefox https://portal.guruja.com.br/aluno/visao-geral"), { description = "guruja" })
hl.unbind("SUPER + SHIFT + H")
hl.bind("SUPER + SHIFT + H", hl.dsp.exec_cmd("helium --new-tab https://github.com/VGViana/dotfilesv1"), { description = "Git" })
hl.unbind("SUPER + SHIFT + L")
hl.bind("SUPER + SHIFT + L", hl.dsp.exec_cmd("helium https://calendar.google.com/calendar/u/0/r?pli=1"), { repeating = true, description = "calendar" })
hl.unbind("SUPER + SHIFT + M")
hl.bind("SUPER + SHIFT + M", hl.dsp.exec_cmd("helium https://mail.google.com/mail/u/0/#inbox"), { description = "mail" })
hl.unbind("SUPER + SHIFT + O")
hl.bind("SUPER + SHIFT + O", hl.dsp.exec_cmd("helium https://open.spotify.com/intl-pt/?flow_ctx=9b691963-a012-4577-a494-4e3b46cbbd60%3A1788550522"))
hl.unbind("SUPER + SHIFT + R")
hl.bind("SUPER + SHIFT + R", hl.dsp.exec_cmd("helium https://www.reddit.com/"), { description = "reddit" })
hl.unbind("SUPER + SHIFT + T")
hl.bind("SUPER + SHIFT + T", hl.dsp.exec_cmd("firefox --new-tab https://www.tecconcursos.com.br/"), { description = "Tec" })
hl.unbind("SUPER + SHIFT + W")
hl.bind("SUPER + SHIFT + W", hl.dsp.exec_cmd("helium --new-tab https://web.whatsapp.com"), { description = "wpp" })
hl.unbind("SUPER + SHIFT + Y")
hl.bind("SUPER + SHIFT + Y", hl.dsp.exec_cmd("helium https://youtube.com"), { description = "yt" })
hl.unbind("SUPER + T")
hl.bind("SUPER + T", hl.dsp.exec_cmd("kitty -e btop"))
hl.unbind("SUPER + Y")
hl.bind("SUPER + Y", hl.dsp.exec_cmd("~/.local/bin/yazi-launch"), { description = "yazi" })
hl.unbind("CTRL + T")
hl.unbind("Print")
hl.unbind("SUPER + CTRL + B")
hl.unbind("SUPER + CTRL + C")
hl.unbind("SUPER + CTRL + D")
hl.unbind("SUPER + CTRL + F")
hl.bind("SUPER + CTRL + F", hl.dsp.window.fullscreen({ mode = "maximized", action = "toggle" }), { description = "Toggle maximization" })
hl.unbind("SUPER + CTRL + I")
hl.unbind("SUPER + CTRL + R")
hl.unbind("SUPER + CTRL + S")
hl.unbind("SUPER + F")
hl.bind("SUPER + F", hl.dsp.window.float({ action = "toggle" }), { description = "Toggle Floating" })
hl.unbind("SUPER + G")
hl.bind("SUPER + G", hl.dsp.group.toggle(), { description = "togglegroup" })
hl.unbind("SUPER + SHIFT + J")
hl.unbind("SUPER + SHIFT + K")
hl.unbind("SUPER + SHIFT + down")
hl.unbind("SUPER + SHIFT + equal")
hl.unbind("SUPER + SHIFT + left")
hl.unbind("SUPER + SHIFT + minus")
hl.unbind("SUPER + Z")
hl.unbind("SUPER + code:20")
hl.unbind("SUPER + code:21")
hl.unbind("SUPER + comma")
hl.unbind("SUPER + equal")
hl.unbind("SUPER + minus")
