-- Auto-generated by DMS Matugen hook — do not edit manually.
-- Remove require("dms.colors") from hyprland.lua to override.

hl.config({
	general = {
		col = {
			active_border = "rgb(83a598)",
			inactive_border = "rgb(7c6f64)",
		},
	},
	group = {
		col = {
			border_active = "rgb(83a598)",
			border_inactive = "rgb(7c6f64)",
			border_locked_active = "rgb(fb4934)",
			border_locked_inactive = "rgb(7c6f64)",
		},
		groupbar = {
			col = {
				active = "rgb(83a598)",
				inactive = "rgb(7c6f64)",
				locked_active = "rgb(fb4934)",
				locked_inactive = "rgb(7c6f64)",
			},
		},
	},
})
