-- Auto-generated by DMS Matugen hook — do not edit manually.
-- Remove require("dms.colors") from hyprland.lua to override.

hl.config({
	general = {
		col = {
			active_border = "rgb(9eac62)",
			inactive_border = "rgb(857866)",
		},
	},
	group = {
		col = {
			border_active = "rgb(9eac62)",
			border_inactive = "rgb(857866)",
			border_locked_active = "rgb(b3261e)",
			border_locked_inactive = "rgb(857866)",
		},
		groupbar = {
			col = {
				active = "rgb(9eac62)",
				inactive = "rgb(857866)",
				locked_active = "rgb(b3261e)",
				locked_inactive = "rgb(857866)",
			},
		},
	},
})
