-- Auto-generated by DMS — do not edit manually

hl.env("HYPRCURSOR_THEME", "Breeze_Light")
hl.env("XCURSOR_THEME", "Breeze_Light")
hl.env("HYPRCURSOR_SIZE", "30")
hl.env("XCURSOR_SIZE", "30")

hl.config({
	cursor = {
		hide_on_key_press = true,
	},
})
