-- Auto-generated by DMS — do not edit manually

hl.config({
	general = {
		gaps_in = 4,
		gaps_out = 4,
		border_size = 4,
		resize_on_border = false,
	},
	decoration = {
		rounding = 0,
	},
})

-- bar-xray off
