-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "eDP-1", mode = "1920x1080@60.001", position = "0x0", scale = 1, vrr = 1 })
hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@100.000", position = "1920x0", scale = 1, vrr = 1 })
