-- Hyprland configuration (Lua) — https://wiki.hypr.land/Configuring/Start/

hl.config({ autogenerated = false })

-- DMS_STARTUP_BEGIN
hl.on("hyprland.start", function()
	hl.exec_cmd("dbus-update-activation-environment --systemd --all")
	hl.exec_cmd("systemctl --user start hyprland-session.target")
end)
-- DMS_STARTUP_END

hl.config({
	input = {
		-- empty inherits XKB_DEFAULT_LAYOUT (libxkbcommon), falls back to "us"
		kb_layout = "br",
		kb_variant = "abnt2",
		kb_options = "ctrl:swapcaps",
		numlock_by_default = true,
		follow_mouse = 1,
		touchpad = {
			tap_to_click = true,
			natural_scroll = false,
		},
	},
	general = {
		gaps_in = 5,
		gaps_out = 5,
		border_size = 2,
		layout = "dwindle",
	},
	decoration = {
		rounding = 12,
		active_opacity = 1.0,
		inactive_opacity = 1.0,
		shadow = {
			enabled = false,
			range = 30,
			render_power = 5,
			offset = "0 5",
			color = "rgba(00000070)",
		},
	},
	misc = {
		disable_hyprland_logo = true,
		disable_splash_rendering = true,
	},
	dwindle = {
		preserve_split = true,
	},
	master = {
		mfact = 0.5,
	},
})

hl.animation({ leaf = "windowsIn", enabled = false, speed = 3, bezier = "default" })
hl.animation({ leaf = "windowsOut", enabled = false, speed = 3, bezier = "default" })
hl.animation({ leaf = "workspaces", enabled = false, speed = 5, bezier = "default" })
hl.animation({ leaf = "windowsMove", enabled = false, speed = 4, bezier = "default" })
hl.animation({ leaf = "fade", enabled = false, speed = 3, bezier = "default" })
hl.animation({ leaf = "border", enabled = false, speed = 3, bezier = "default" })

hl.window_rule({ match = { class = "^(org\\.wezfurlong\\.wezterm)$" }, tile = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.)" }, rounding = 12 })
hl.window_rule({ match = { class = "^(gnome-control-center)$" }, tile = true })
hl.window_rule({ match = { class = "^(pavucontrol)$" }, tile = true })
hl.window_rule({ match = { class = "^(nm-connection-editor)$" }, tile = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.Calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(gnome-calculator)$" }, float = true })
hl.window_rule({ match = { class = "^(galculator)$" }, float = true })
hl.window_rule({ match = { class = "^(blueman-manager)$" }, float = true })
hl.window_rule({ match = { class = "^(org\\.gnome\\.Nautilus)$" }, float = true })
hl.window_rule({ match = { class = "^(xdg-desktop-portal)$" }, float = true })
hl.window_rule({
	match = { class = "^(steam)$", title = "^(notificationtoasts)" },
	no_initial_focus = true,
	pin = true,
})
hl.window_rule({
	match = { class = "^(firefox)$", title = "^(Picture-in-Picture)$" },
	float = true,
})
hl.window_rule({ match = { class = "^(zoom)$" }, float = true })
hl.layer_rule({ match = { namespace = "^(quickshell)$" }, no_anim = true })
hl.layer_rule({ match = { namespace = "^dms:.*" }, no_anim = true })

require("dms.colors")
require("dms.outputs")
require("dms.layout")
require("dms.cursor")
require("dms.binds")
require("dms.binds-user")
require("dms.windowrules")

-- ============================================================
-- LAPTOP LID / EXTERNAL MONITOR
-- ============================================================

-- Tampa fechada:
--   - desabilita a tela interna
--   - coloca o LG sozinho em 1920x1080@100
hl.bind(
	"switch:on:Lid Switch",
	hl.dsp.exec_cmd(
		'hyprctl eval \'hl.monitor({ output = "eDP-1", disabled = true }); hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@100", position = "0x0", scale = 1 })\''
	)
)

-- Tampa aberta:
--   - reativa a tela interna em 1920x1080@60
--   - coloca o LG à direita em 1920x1080@100
hl.bind(
	"switch:off:Lid Switch",
	hl.dsp.exec_cmd(
		'sleep 1; hyprctl eval \'hl.monitor({ output = "eDP-1", mode = "1920x1080@60", position = "0x0", scale = 1 }); hl.monitor({ output = "HDMI-A-1", mode = "1920x1080@100", position = "1920x0", scale = 1 })\''
	)
)
